export_path: './exports'
model_path: './saved_models/best_model.pth'
quantization_dataset:
  module_name: src.data.sets.default
  class_name: DefaultDataset
  parameters:
    data_folder: ./val_data_dir
    num_samples: 100
model:
  class_name: DefaultCNN
  module_name: src.models.default
  parameters:
